services:
  db:
    image: "mariadb"
    restart: "always"
    env_file:
      - ~/env_file
    ports:
      - 3306
    volumes:
      - db-config:~/db/config
      - db-data:~/db/data
    networks: 
      - db-backend

  backend:
    build: .
    env_file:
      - ~/env_file
    ports:
      - 8080
    depends_on:
      - db
    networks:
      - db-backend
      - proxiable
volumes:
  db-config:
  db-data:

networks:
  db-backend:
  proxiable: